language: cpp
compiler:
    - clang
notifications:
    email: false
env:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
matrix:
    allow_failures:
      - env: JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev gfortran libcr-dev mpich2 mpich2-doc julia -y
script:
    - julia -e 'Pkg.init(); Pkg.clone("https://github.com/jgoldfar/XBraid.jl.git"); Pkg.build("XBraid")'
    - julia -e 'using XBraid; @assert isdefined(:XBraid); @assert typeof(XBraid) === Module'
    - if [ $JULIAVERSION = "juliareleases" ]; then julia --code-coverage test/runtests.jl; fi
    - if [ $JULIAVERSION = "julianightlies" ]; then julia test/runtests.jl; fi
after_success:
    - if [ $JULIAVERSION = "juliareleases" ]; then julia -e 'cd(Pkg.dir("XBraid")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
